mqtt:
  broker: 10.3.141.151
  node_id: mqtt_mesh
mesh:
  hallway_back_light:
    uuid: 3f557c74-f326-7e39-b8ed-472cca61e9cd
    name: Hallway Back Light
  hallway_front_light:
    uuid: e0827bfb-db9d-ea3c-919e-137252c62f6f
    name: Hallway Front Light
  kitchen_table_light:
    uuid: ecce3aa9-3915-5236-b795-4a2bb919b83f
    name: Kitchen Table Light
  kitchen_countertop_left_light:
    uuid: 0355c382-6ff3-2330-8fca-6face349427a
    name: Kitchen Countertop Left Light
  kitchen_countertop_right_light:
    uuid: 0118d7b3-1494-fa32-8538-51bb39d21071
    name: Kitchen Countertop Right Light
  work_room_light:
    uuid: e6a7af68-7177-c032-a149-33618817359c
    name: Work Room Light
